import { Inter } from "next/font/google";
import "./globals.css";
import { Grid, Stack, Typography, Box } from "@mui/material";
import Link from "next/link";
import Header from "./components/app.header";
import Footer from "./components/app.footer";
import Sidebar from "./components/app.sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        <Box component="main" sx={{ flexGrow: 1, padding: 3 , direction:"row" }} >
          <Grid container spacing={3}>
            <Grid item xs={3}>
              <Sidebar />
            </Grid>
            <Grid item xs={9}>
              {children}
            </Grid>
          </Grid>
        </Box>
        <Footer />
      </body>
    </html>
  );
}
