"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { Grid, Box, Stack } from "@mui/material";
import Header from "./components/app.header";
import Footer from "./components/app.footer";
import Sidebar from "./components/app.sidebar";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const renderMenu = () => {
    if (pathname === "/") {
      return null;
    } else {
      return <Sidebar />;
    }
  };

  const menu = renderMenu();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Box component="main" sx={{ flexGrow: 1, padding: 3 }}>
          <Grid container spacing={3}>
            {menu && (
              <Grid item xs={3}>
                {menu}
              </Grid>
            )}
            <Grid
              item
              xs={menu ? 9 : 12}
              // style={{
              //   justifyContent: "center",
              //   display: "flex",
              //   alignItems: "center",
              // }}
            >
              {children}
            </Grid>
          </Grid>
        </Box>
        <Footer />
      </body>
    </html>
  );
}
